# Apps
$terminal = ghostty
$menu = sherlock
$browser =

$mod1 = ALT
$mod2 = ALT_SUPER

# Launchers
bind = $mod1, return, exec, $terminal
bind = $mod1, space, exec, $menu

# Clipboard history
bind = $mod1, v, exec, cliphist list | sherlock --dmenu | cliphist decode | wl-copy

# General
bind = $mod1, c, killactive,
# bind = $mod1, m, exit,
bind = $mod1, w, togglefloating
bind = $mod2, w, fullscreen, 0

# Layouts
bind = $mod1, z, pseudo, # dwindle
bind = $mod1, x, togglesplit, # dwindle

# Groups
bind = $mod1, G, togglegroup

# vim motion window navigation
bind = $mod1, H, movefocus, l
bind = $mod1, L, movefocus, r
bind = $mod1, K, movefocus, u
bind = $mod1, J, movefocus, d
# vim motion window movement
bind = $mod2, H, movewindow, l
bind = $mod2, L, movewindow, r
bind = $mod2, K, movewindow, u
bind = $mod2, J, movewindow, d


# Tab through workspaces
bind = $mod1, Tab, cyclenext
bind = $mod1, Tab, bringactivetotop

# right hand
bind = $mod1, y, workspace, 1
bind = $mod1, u, workspace, 2
bind = $mod1, i, workspace, 3
bind = $mod1, o, workspace, 4
bind = $mod1, p, workspace, 5
bind = $mod1, n, workspace, 6
bind = $mod1, m, workspace, 7
bind = $mod1, comma, workspace, 8
bind = $mod1, period, workspace, 9
bind = $mod1, slash, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mod2, y, movetoworkspace, 1
bind = $mod2, u, movetoworkspace, 2
bind = $mod2, i, movetoworkspace, 3
bind = $mod2, o, movetoworkspace, 4
bind = $mod2, p, movetoworkspace, 5
bind = $mod2, n, movetoworkspace, 6
bind = $mod2, m, movetoworkspace, 7
bind = $mod2, comma, movetoworkspace, 8
bind = $mod2, period, movetoworkspace, 9
bind = $mod2, slash, movetoworkspace, 10

# Window Resizing with Arrow Keys
bind = $mod1, left, resizeactive, -25 0
bind = $mod1, right, resizeactive, 25 0
bind = $mod1, up, resizeactive, 0 -25 
bind = $mod1, down, resizeactive, 0 25


# Example special workspace (scratchpad)
bind = $mod1, S, togglespecialworkspace, magic
bind = $mod2, S, movetoworkspace, special:magic


# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mod1, mouse:272, movewindow
bindm = $mod1, mouse:273, resizewindow

# Requires playerctl
bind = $mod1, ', exec, pamixer -i 5
bind = $mod1, ;, exec, pamixer -d 5
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5
bind = , XF86AudioLowerVolume, exec, pamixer -d 5
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPause, exec, playerctl play-pause
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioPrev, exec, playerctl previous

