# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/

#  Options
#  w:window-count[t:tiled,f:floating,g:countGroupsNotWindows,v:onlyVisible]
#  f:fullscreen[-1:noFull,0:full,1:maximized,2:fullStateless]
#  s:special?[bool]
#  m: monitor[monitor]
#  n: namedAction

# Set Default Workspaces
workspace = 1, monitor:DP-1, default:true, persistent:true
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1

# Specific App Workspaces
workspace = 10, on-created-empty:vesktop
# Smart Gaps (Ignores Special Workspaces)
workspace = w[tv1]s[false], gapsout:0, gapsin:0
workspace = f[1]s[false], gapsout:0, gapsin:0
windowrule = bordersize 0, floating:0, onworkspace:w[tv1]s[false]
windowrule = rounding 0, floating:0, onworkspace:w[tv1]s[false]
windowrule = bordersize 0, floating:0, onworkspace:f[1]s[false]
windowrule = rounding 0, floating:0, onworkspace:f[1]s[false]


