monitor = DP-1, 2560x1440@75, 2560x0, 1
monitor = HDMI-A-1, 2560x1440@144, 0x0, 1

input {
  kb_layout = us
  repeat_delay = 250
  repeat_rate = 33
  follow_mouse = 2
  sensitivity = 0
}

# activity manager
exec-once = systemctl --user start hyprpolkitagent
# init vicinae picker
exec-once = vicinae server
exec-once = netbird-ui
# wallpaper
exec-once = swww-daemon
exec-once = swww --restore
# notification
exec-once = mako
# statusbar
exec-once = waybar
# idle and lock manager
exec-once = hypridle &

# See https://wiki.hyprland.org/Configuring/Environment-variables/
# hypr
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyperland
env = HYPERSHOT_DIR,~/pictures/screenshots/
# cursor settings
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = HYPRCURSOR_THEME,rose-pine-hyprcursor
# env = HYPRCURSOR_THEME,Nordzy-hyprcursors
env = ELECTRON_OZONE_PLATFORM_HINT,auto
# gpu settings
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __GL_VRR_ALLOWED,0
env = NVD_BACKEND,direct
