general {
  lock_cmd = pidof hyprlock || hyprlock # use running hyprlock or start it
  before_sleep_cmd = loginctl lock-session 
  after_sleep_cmd = hyprctl dispatch dpms on
}

# lock warning
listener {
  timeout = 240 # 4 min
  on-timeout = notify-send "Locking in 60 seconds..."
  on-resume = notify-send "Lock canceled"
}

# lock screen
listener {
  timeout = 300 # 5 min
  on-timeout = loginctl lock-session
}

# monitor off
listener {
  timeout = 330 # 5.5 min
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

# suspend pc
listener {
  timeout = 1800 # 30 min
  on-timeout = systemctl suspend
}
