# Hypr Path
$CONF = ~/.config/hypr/
source = $CONF/core.conf
source = $CONF/workspaces.conf
source = $CONF/keymaps.conf
source = $CONF/theme.conf

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    allow_small_split = true
    mfact = 0.6
    new_status = slave
    new_on_top = true
    smart_resizing = true
    orientation = center
    slave_count_for_center_master = 3
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}
