# app aliases
$terminal = ghostty
$browser = firefox-developer-edition
$picker = vicinae

# Mod Keys
$mod = ALT
$mod2 = ALT_SUPER
$smod = SHIFT_ALT

bind = $mod, return, exec, $terminal
bind = $mod, space, exec, $picker toggle    # vicinae app laucncher

# Clipboard history
bind = $mod, v, exec, vicinae vicinae://extensions/vicinae/clipboard/history

# General
bind = $mod, q, killactive,
# bind = $mod, w, exit,
bind = $mod,  f, togglefloating
bind = $mod, z, fullscreen, 0

# Layouts
bind = $mod, d, pseudo, # dwindle
bind = $mod, x, togglesplit, # dwindle

# Groups
bind = $mod, g, togglegroup

# vim motion window navigation
bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d
# vim motion window movement
bind = $mod2, H, movewindow, l
bind = $mod2, L, movewindow, r
bind = $mod2, K, movewindow, u
bind = $mod2, J, movewindow, d


# Tab through workspaces
bind = $mod, Tab, cyclenext
bind = $mod, Tab, bringactivetotop

# right hand
bind = $mod, y, workspace, 1
bind = $mod, u, workspace, 2
bind = $mod, i, workspace, 3
bind = $mod, o, workspace, 4
bind = $mod, p, workspace, 5
bind = $mod, n, workspace, 6
bind = $mod, m, workspace, 7
bind = $mod, comma, workspace, 8
bind = $mod, period, workspace, 9
bind = $mod, slash, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mod2, y, movetoworkspace, 1
bind = $mod2, u, movetoworkspace, 2
bind = $mod2, i, movetoworkspace, 3
bind = $mod2, o, movetoworkspace, 4
bind = $mod2, p, movetoworkspace, 5
bind = $mod2, n, movetoworkspace, 6
bind = $mod2, m, movetoworkspace, 7
bind = $mod2, comma, movetoworkspace, 8
bind = $mod2, period, movetoworkspace, 9
bind = $mod2, slash, movetoworkspace, 10

# Window Resizing with Arrow Keys
bind = $mod, left, resizeactive, -25 0
bind = $mod, right, resizeactive, 25 0
bind = $mod, up, resizeactive, 0 -25 
bind = $mod, down, resizeactive, 0 25

# Example special workspace (scratchpad)
bind = $mod, S, togglespecialworkspace, magic
bind = $mod2, S, movetoworkspace, special:magic

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Requires playerctl
# bind = $mod, ', exec, pamixer -i 5
# bind = $mod, ;, exec, pamixer -d 5
# bind = , XF86AudioRaiseVolume, exec, pamixer -i 5
# bind = , XF86AudioLowerVolume, exec, pamixer -d 5
# bind = , XF86AudioNext, exec, playerctl next
# bind = , XF86AudioPause, exec, playerctl play-pause
# bind = , XF86AudioPlay, exec, playerctl play-pause
# bind = , XF86AudioPrev, exec, playerctl previous
