# Floats
## mpv
windowrule = float,title:(*mpv*)
windowrulev2 = size 1920 1080,title:(*mpv*)

## Volume Control
windowrule = float, center, title:(^Volume Control$),
windowrule =  size 1050 900, title:(^Volume Control$),

# Recomeneded defaults
## Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*
## Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
